import Header from "@/components/Header";
import "../globals.css";
import type { Metadata } from "next";
import SideBarPanelAdministracion from "@/components/SideBar-PanelAdministracion";

export const metadata: Metadata = {
   title: "Hospedaje El Rinconcito",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <main className="lg:flex bg-zinc-950 text-white">
         <SideBarPanelAdministracion />
         {children}
      </main>
   );
}
